import { Figure } from "@/types";

export const FIGURES: Figure[] = [
  // --- Biblical: Old Testament ---
  { id: "adam", name: "Adam", descriptor: "First Man, Garden of Eden", era: "Biblical" },
  { id: "eve", name: "Eve", descriptor: "First Woman, Garden of Eden", era: "Biblical" },
  { id: "noah", name: "Noah", descriptor: "Builder of the Ark, Genesis", era: "Biblical" },
  { id: "abraham", name: "Abraham", descriptor: "Father of Nations, Genesis", era: "Biblical" },
  { id: "sarah", name: "Sarah", descriptor: "Wife of Abraham, Mother of Isaac", era: "Biblical" },
  { id: "isaac", name: "Isaac", descriptor: "Son of Abraham, Patriarch", era: "Biblical" },
  { id: "jacob", name: "Jacob", descriptor: "Patriarch, Father of the Twelve Tribes", era: "Biblical" },
  { id: "joseph", name: "Joseph", descriptor: "Son of Jacob, Dreamer & Ruler of Egypt", era: "Biblical" },
  { id: "moses", name: "Moses", descriptor: "Prophet & Lawgiver, Led the Exodus", era: "Biblical" },
  { id: "miriam", name: "Miriam", descriptor: "Prophetess, Sister of Moses", era: "Biblical" },
  { id: "joshua", name: "Joshua", descriptor: "Military Leader, Conquered Canaan", era: "Biblical" },
  { id: "deborah", name: "Deborah", descriptor: "Judge & Prophetess of Israel", era: "Biblical" },
  { id: "gideon", name: "Gideon", descriptor: "Judge & Military Leader of Israel", era: "Biblical" },
  { id: "samson", name: "Samson", descriptor: "Judge of Israel, Man of Great Strength", era: "Biblical" },
  { id: "ruth", name: "Ruth", descriptor: "Moabite Woman, Model of Loyalty & Faith", era: "Biblical" },
  { id: "samuel", name: "Samuel", descriptor: "Prophet & Last Judge of Israel", era: "Biblical" },
  { id: "saul", name: "King Saul", descriptor: "First King of Israel", era: "Biblical" },
  { id: "david", name: "King David", descriptor: "King of Israel, Psalmist & Warrior", era: "Biblical" },
  { id: "solomon", name: "King Solomon", descriptor: "King of Israel, Wisest Man Who Ever Lived", era: "Biblical" },
  { id: "elijah", name: "Elijah", descriptor: "Prophet, Called Fire from Heaven", era: "Biblical" },
  { id: "elisha", name: "Elisha", descriptor: "Prophet, Successor of Elijah", era: "Biblical" },
  { id: "isaiah", name: "Isaiah", descriptor: "Major Prophet, Foretold the Messiah", era: "Biblical" },
  { id: "jeremiah", name: "Jeremiah", descriptor: "The Weeping Prophet", era: "Biblical" },
  { id: "ezekiel", name: "Ezekiel", descriptor: "Prophet of Visions & Restoration", era: "Biblical" },
  { id: "daniel", name: "Daniel", descriptor: "Prophet, Interpreter of Dreams, Lion's Den", era: "Biblical" },
  { id: "jonah", name: "Jonah", descriptor: "Prophet Swallowed by a Great Fish", era: "Biblical" },
  { id: "job", name: "Job", descriptor: "Man of Suffering & Enduring Faith", era: "Biblical" },
  { id: "esther", name: "Esther", descriptor: "Jewish Queen of Persia, Savior of Her People", era: "Biblical" },
  { id: "nehemiah", name: "Nehemiah", descriptor: "Governor, Rebuilder of Jerusalem's Walls", era: "Biblical" },
  { id: "ezra", name: "Ezra", descriptor: "Priest & Scribe, Restorer of the Law", era: "Biblical" },
  { id: "hosea", name: "Hosea", descriptor: "Prophet of God's Unfailing Love", era: "Biblical" },
  { id: "amos", name: "Amos", descriptor: "Prophet of Justice & Righteousness", era: "Biblical" },
  { id: "micah", name: "Micah", descriptor: "Prophet, Foretold Messiah's Birth in Bethlehem", era: "Biblical" },
  { id: "habakkuk", name: "Habakkuk", descriptor: "Prophet Who Wrestled with God's Justice", era: "Biblical" },
  // --- Biblical: New Testament ---
  { id: "jesus", name: "Jesus of Nazareth", descriptor: "Son of God, Savior, Rabbi & Teacher", era: "Biblical" },
  { id: "mary-mother", name: "Mary, Mother of Jesus", descriptor: "Mother of Jesus, Blessed Among Women", era: "Biblical" },
  { id: "joseph-nt", name: "Joseph of Nazareth", descriptor: "Carpenter, Earthly Father of Jesus", era: "Biblical" },
  { id: "john-the-baptist", name: "John the Baptist", descriptor: "Prophet, Forerunner of Jesus", era: "Biblical" },
  { id: "peter", name: "Simon Peter", descriptor: "Apostle, Rock of the Church", era: "Biblical" },
  { id: "paul", name: "Paul the Apostle", descriptor: "Apostle to the Gentiles, Author of Many Epistles", era: "Biblical" },
  { id: "john-apostle", name: "John the Apostle", descriptor: "Beloved Disciple, Author of Revelation", era: "Biblical" },
  { id: "james-apostle", name: "James, Son of Zebedee", descriptor: "Apostle, First Martyred Apostle", era: "Biblical" },
  { id: "matthew", name: "Matthew", descriptor: "Apostle & Gospel Writer, Former Tax Collector", era: "Biblical" },
  { id: "luke", name: "Luke the Evangelist", descriptor: "Physician & Gospel Writer", era: "Biblical" },
  { id: "thomas", name: "Thomas the Apostle", descriptor: "Apostle Known as Doubting Thomas", era: "Biblical" },
  { id: "barnabas", name: "Barnabas", descriptor: "Apostle & Missionary Partner of Paul", era: "Biblical" },
  { id: "stephen-martyr", name: "Stephen", descriptor: "First Christian Martyr", era: "Biblical" },
  { id: "mary-magdalene", name: "Mary Magdalene", descriptor: "Follower of Jesus, First Witness of the Resurrection", era: "Biblical" },
  { id: "lazarus", name: "Lazarus of Bethany", descriptor: "Raised from the Dead by Jesus", era: "Biblical" },
  { id: "nicodemus", name: "Nicodemus", descriptor: "Pharisee & Secret Follower of Jesus", era: "Biblical" },
  { id: "zacchaeus", name: "Zacchaeus", descriptor: "Tax Collector Transformed by Jesus", era: "Biblical" },
  { id: "priscilla", name: "Priscilla", descriptor: "Early Church Leader & Teacher", era: "Biblical" },
  { id: "timothy", name: "Timothy", descriptor: "Young Pastor, Paul's Protégé", era: "Biblical" },
  // --- Ancient History ---
  { id: "socrates", name: "Socrates", descriptor: "Greek Philosopher, 470–399 BC", era: "Ancient" },
  { id: "plato", name: "Plato", descriptor: "Greek Philosopher, 428–348 BC", era: "Ancient" },
  { id: "aristotle", name: "Aristotle", descriptor: "Greek Philosopher, 384–322 BC", era: "Ancient" },
  { id: "cleopatra", name: "Cleopatra VII", descriptor: "Pharaoh of Egypt, 69–30 BC", era: "Ancient" },
  { id: "julius-caesar", name: "Julius Caesar", descriptor: "Roman General & Statesman, 100–44 BC", era: "Ancient" },
  { id: "sun-tzu", name: "Sun Tzu", descriptor: "Military Strategist & Author, 544–496 BC", era: "Ancient" },
  { id: "confucius", name: "Confucius", descriptor: "Chinese Philosopher, 551–479 BC", era: "Ancient" },
  { id: "alexander-the-great", name: "Alexander the Great", descriptor: "Macedonian King & Conqueror, 356–323 BC", era: "Ancient" },
  { id: "marcus-aurelius", name: "Marcus Aurelius", descriptor: "Roman Emperor & Stoic Philosopher, 121–180 AD", era: "Ancient" },
  // --- Renaissance / Early Modern ---
  { id: "leonardo-da-vinci", name: "Leonardo da Vinci", descriptor: "Renaissance Polymath, 1452–1519", era: "Renaissance" },
  { id: "galileo", name: "Galileo Galilei", descriptor: "Astronomer & Physicist, 1564–1642", era: "Early Modern" },
  { id: "william-shakespeare", name: "William Shakespeare", descriptor: "Playwright & Poet, 1564–1616", era: "Early Modern" },
  { id: "isaac-newton", name: "Isaac Newton", descriptor: "Mathematician & Physicist, 1643–1727", era: "Early Modern" },
  { id: "martin-luther", name: "Martin Luther", descriptor: "Theologian & Reformation Leader, 1483–1546", era: "Renaissance" },
  // --- 18th Century ---
  { id: "benjamin-franklin", name: "Benjamin Franklin", descriptor: "Statesman & Inventor, 1706–1790", era: "18th Century" },
  { id: "napoleon", name: "Napoleon Bonaparte", descriptor: "French Emperor, 1769–1821", era: "18th Century" },
  { id: "mary-wollstonecraft", name: "Mary Wollstonecraft", descriptor: "Philosopher & Author, 1759–1797", era: "18th Century" },
  // --- 19th Century ---
  { id: "charles-darwin", name: "Charles Darwin", descriptor: "Naturalist & Biologist, 1809–1882", era: "19th Century" },
  { id: "abraham-lincoln", name: "Abraham Lincoln", descriptor: "16th US President, 1809–1865", era: "19th Century" },
  { id: "harriet-tubman", name: "Harriet Tubman", descriptor: "Abolitionist & Activist, 1822–1913", era: "19th Century" },
  { id: "friedrich-nietzsche", name: "Friedrich Nietzsche", descriptor: "Philosopher, 1844–1900", era: "19th Century" },
  { id: "nikola-tesla", name: "Nikola Tesla", descriptor: "Inventor & Engineer, 1856–1943", era: "19th Century" },
  { id: "sigmund-freud", name: "Sigmund Freud", descriptor: "Founder of Psychoanalysis, 1856–1939", era: "19th Century" },
  { id: "dwl-moody", name: "D.L. Moody", descriptor: "Evangelist & Founder of Moody Bible Institute, 1837–1899", era: "19th Century" },
  { id: "charles-spurgeon", name: "Charles Spurgeon", descriptor: "The Prince of Preachers, 1834–1892", era: "19th Century" },
  // --- 20th Century ---
  { id: "marie-curie", name: "Marie Curie", descriptor: "Physicist & Chemist, 1867–1934", era: "20th Century" },
  { id: "albert-einstein", name: "Albert Einstein", descriptor: "Theoretical Physicist, 1879–1955", era: "20th Century" },
  { id: "virginia-woolf", name: "Virginia Woolf", descriptor: "Author & Modernist, 1882–1941", era: "20th Century" },
  { id: "mahatma-gandhi", name: "Mahatma Gandhi", descriptor: "Political Leader & Activist, 1869–1948", era: "20th Century" },
  { id: "winston-churchill", name: "Winston Churchill", descriptor: "British Prime Minister, 1874–1965", era: "20th Century" },
  { id: "alan-turing", name: "Alan Turing", descriptor: "Mathematician & Computer Scientist, 1912–1954", era: "20th Century" },
  { id: "rosa-parks", name: "Rosa Parks", descriptor: "Civil Rights Activist, 1913–2005", era: "20th Century" },
  { id: "martin-luther-king", name: "Martin Luther King Jr.", descriptor: "Minister & Civil Rights Leader, 1929–1968", era: "20th Century" },
  { id: "john-f-kennedy", name: "John F. Kennedy", descriptor: "35th US President, 1917–1963", era: "20th Century" },
  { id: "nelson-mandela", name: "Nelson Mandela", descriptor: "South African President & Activist, 1918–2013", era: "20th Century" },
  { id: "stephen-hawking", name: "Stephen Hawking", descriptor: "Theoretical Physicist & Cosmologist, 1942–2018", era: "20th Century" },
  { id: "maya-angelou", name: "Maya Angelou", descriptor: "Poet & Civil Rights Activist, 1928–2014", era: "20th Century" },
  { id: "carl-sagan", name: "Carl Sagan", descriptor: "Astronomer & Author, 1934–1996", era: "20th Century" },
  { id: "frida-kahlo", name: "Frida Kahlo", descriptor: "Painter & Icon, 1907–1954", era: "20th Century" },
  { id: "c-s-lewis", name: "C.S. Lewis", descriptor: "Author & Christian Apologist, 1898–1963", era: "20th Century" },
  { id: "billy-graham", name: "Billy Graham", descriptor: "Evangelist, The Pastor of Presidents, 1918–2018", era: "20th Century" },
  { id: "corrie-ten-boom", name: "Corrie ten Boom", descriptor: "Holocaust Survivor & Christian Author, 1892–1983", era: "20th Century" },
  { id: "dietrich-bonhoeffer", name: "Dietrich Bonhoeffer", descriptor: "Theologian & Martyr, 1906–1945", era: "20th Century" },
  { id: "mother-teresa", name: "Mother Teresa", descriptor: "Catholic Saint & Humanitarian, 1910–1997", era: "20th Century" },
  { id: "cs-lewis", name: "G.K. Chesterton", descriptor: "Author & Christian Apologist, 1874–1936", era: "20th Century" },
  // --- Contemporary ---
  { id: "elon-musk", name: "Elon Musk", descriptor: "Entrepreneur & CEO of Tesla & SpaceX, 1971–", era: "Contemporary" },
  { id: "oprah-winfrey", name: "Oprah Winfrey", descriptor: "Media Executive & Philanthropist, 1954–", era: "Contemporary" },
  { id: "malala-yousafzai", name: "Malala Yousafzai", descriptor: "Education Activist & Nobel Laureate, 1997–", era: "Contemporary" },
  { id: "michelle-obama", name: "Michelle Obama", descriptor: "Attorney & Former First Lady, 1964–", era: "Contemporary" },
  { id: "barack-obama", name: "Barack Obama", descriptor: "44th US President, 1961–", era: "Contemporary" },
  { id: "ruth-bader-ginsburg", name: "Ruth Bader Ginsburg", descriptor: "Supreme Court Justice, 1933–2020", era: "Contemporary" },
  { id: "joby-martin", name: "Joby Martin", descriptor: "Lead Pastor of The Church of Eleven22, 1977–", era: "Contemporary" },
  { id: "david-goggins", name: "David Goggins", descriptor: "Retired Navy SEAL, Ultra-Endurance Athlete & Author, 1975–", era: "Contemporary" },
  { id: "gary-vaynerchuk", name: "Gary Vaynerchuk", descriptor: "Entrepreneur, CEO of VaynerMedia & Author, 1975–", era: "Contemporary" },
  { id: "ed-mylett", name: "Ed Mylett", descriptor: "Peak Performance Coach, Entrepreneur & Author, 1971–", era: "Contemporary" },
  { id: "joe-rogan", name: "Joe Rogan", descriptor: "Comedian, UFC Commentator & Host of The Joe Rogan Experience, 1967–", era: "Contemporary" },
  { id: "jordan-peterson", name: "Jordan Peterson", descriptor: "Psychologist, Author & Cultural Commentator, 1962–", era: "Contemporary" },
  { id: "tony-robbins", name: "Tony Robbins", descriptor: "Life Coach, Author & Motivational Speaker, 1960–", era: "Contemporary" },
  { id: "tim-tebow", name: "Tim Tebow", descriptor: "Former NFL Quarterback, Athlete & Christian Speaker, 1987–", era: "Contemporary" },
  { id: "andy-stanley", name: "Andy Stanley", descriptor: "Pastor of North Point Community Church & Author, 1958–", era: "Contemporary" },
  { id: "rick-warren", name: "Rick Warren", descriptor: "Pastor of Saddleback Church, Author of The Purpose Driven Life, 1954–", era: "Contemporary" },
  { id: "td-jakes", name: "T.D. Jakes", descriptor: "Bishop, Pastor & Author, 1957–", era: "Contemporary" },
];

export const FEATURED_FIGURES: Figure[] = [
  FIGURES.find(f => f.id === "jesus")!,
  FIGURES.find(f => f.id === "paul")!,
  FIGURES.find(f => f.id === "david")!,
  FIGURES.find(f => f.id === "moses")!,
  FIGURES.find(f => f.id === "joby-martin")!,
  FIGURES.find(f => f.id === "david-goggins")!,
  FIGURES.find(f => f.id === "gary-vaynerchuk")!,
  FIGURES.find(f => f.id === "ed-mylett")!,
  FIGURES.find(f => f.id === "joe-rogan")!,
  FIGURES.find(f => f.id === "socrates")!,
  FIGURES.find(f => f.id === "albert-einstein")!,
  FIGURES.find(f => f.id === "martin-luther-king")!,
];

export function searchFigures(query: string): Figure[] {
  const q = query.toLowerCase().trim();
  if (!q) return FEATURED_FIGURES;
  return FIGURES.filter(
    f =>
      f.name.toLowerCase().includes(q) ||
      f.descriptor.toLowerCase().includes(q) ||
      (f.era?.toLowerCase().includes(q) ?? false)
  ).slice(0, 12);
}
